# permissions for end users to view ryans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ryan-viewer-role
rules:
- apiGroups:
  - practice.shipa.io
  resources:
  - ryans
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - practice.shipa.io
  resources:
  - ryans/status
  verbs:
  - get
